BEGIN
  FOR JOB_ROW IN (SELECT JOB
                    FROM USER_JOBS
                   WHERE WHAT LIKE '%DRIVER_WARNNING_SYNC_PROCESS%') LOOP
    DBMS_JOB.REMOVE(JOB_ROW.JOB);
  END LOOP;
  COMMIT;
END;
/

DECLARE
  job2010 NUMBER;

BEGIN
  DBMS_JOB.SUBMIT(job2010,
'/**每隔1天凌晨1:00统计预警数据**/DRIVER_WARNNING_SYNC_PROCESS();',sysdate,'TRUNC(SYSDATE+1)+1/24');
END;
/ 
commit;