drop VIEW V_DRIVER_CONVERT;
drop VIEW V_DRIVER_CONVERT_BAK;
drop procedure HANDLE_DRIVE_CONVER_DATA;
BEGIN
  FOR JOB_ROW IN (SELECT JOB
                    FROM USER_JOBS
                   WHERE WHAT LIKE '%HANDLE_DRIVE_CONVER_DATA%') LOOP
    DBMS_JOB.REMOVE(JOB_ROW.JOB);
  END LOOP;
  COMMIT;
END;
/


