package com.sf.module.esbinterface.webservice.stub.bigfileservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-09-12T18:36:10.734+08:00
 * Generated source version: 2.7.10
 */
@WebService(targetNamespace = "http://www.sf-express.com/esb/service/BigFileService/wsdl", name = "BigFileServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BigFileServicePortType {

    @RequestWrapper(localName = "BigFileService", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService", className = "com.sf.module.esbinterface.webservice.stub.bigfileservice.BigFileServiceTYPE")
    @WebMethod(operationName = "BigFileService", action = "urn:BigFileService/1/")
    @ResponseWrapper(localName = "BigFileServiceResponse", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService", className = "com.sf.module.esbinterface.webservice.stub.bigfileservice.BigFileServiceResponseTYPE")
    public void bigFileService(
            @WebParam(name = "SHEAD", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService")
            com.sf.module.esbinterface.webservice.stub.bigfileservice.SHEADType1 shead,
            @WebParam(name = "SBODY", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService")
            com.sf.module.esbinterface.webservice.stub.bigfileservice.SBODYType2 sbody,
            @WebParam(name = "esbSoapHeader", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService", header = true)
            EsbSoapHeaderType esbSoapHeader1,
            @WebParam(mode = WebParam.Mode.OUT, name = "SHEAD", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService")
            javax.xml.ws.Holder<SHEADType3> shead1,
            @WebParam(mode = WebParam.Mode.OUT, name = "SBODY", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService")
            javax.xml.ws.Holder<SBODYType5> sbody1,
            @WebParam(mode = WebParam.Mode.OUT, name = "esbSoapHeader", targetNamespace = "http://www.sf-express.com/esb/service/BigFileService", header = true)
            javax.xml.ws.Holder<EsbSoapHeaderType> esbSoapHeader2
    );
}
