alter table OP_ATTENDANCE_COUNT_REPORT drop column COM_FULL_ATTENDANCE_NUM ;

alter table OP_ATTENDANCE_COUNT_REPORT drop column COM_NOT_FULL_ATTENDANCE_NUM ;

alter table OP_ATTENDANCE_COUNT_REPORT drop column COM_OUT_ATTENDANCE_NUM;

