
DECLARE job2010 NUMBER;

BEGIN
 DBMS_JOB.SUBMIT(job2010,'/**每天4:00扫描网点表，将新增网点授权给相应用户**/STP_CMS_ADD_ACCR_DEPTS;STP_CMS_ADD_USER_DEPTS;' ,sysdate,'TRUNC(SYSDATE+1)+4/24');
END;
/
commit;

DECLARE JOB_PMP2SPMS_EMP3 NUMBER;
BEGIN 
    SYS.DBMS_JOB.SUBMIT(JOB_PMP2SPMS_EMP3, '/**每天3:00将PMP人员数据同步至人员表**/PMP_SYNCHRONOUS_TO_SPMS;', SYSDATE, 'TRUNC(SYSDATE+1)+3/24');
    COMMIT;
END;
/

DECLARE JOB_PMP2SPMS_EMP15 NUMBER;
BEGIN 
    SYS.DBMS_JOB.SUBMIT(JOB_PMP2SPMS_EMP15, '/**每天15:00将PMP人员数据同步至人员表**/PMP_SYNCHRONOUS_TO_SPMS;', SYSDATE, 'TRUNC(SYSDATE+1)+15/24');
    COMMIT;
END;
/