package com.sf.module.esbinterface.webservice.stub.fileResendServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Tue Aug 26 14:45:32 CST 2014
 * Generated source version: 2.2.10
 */

@WebService(targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ESBServerPortType {

    @RequestWrapper(localName = "FileResendService", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices", className = "com.sf.module.esbinterface.webservice.stub.fileResendServices.FileResendServiceBodyType")
    @WebMethod(operationName = "FileResendService", action = "urn:/FileResendService")
    @ResponseWrapper(localName = "FileResendServiceResponse", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices", className = "com.sf.module.esbinterface.webservice.stub.fileResendServices.FileResendServiceResponseBodyType")
    public void fileResendService(
            @WebParam(name = "SHEAD", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices")
            com.sf.module.esbinterface.webservice.stub.fileResendServices.FileResendServiceBodyType.SHEAD shead,
            @WebParam(name = "SBODY", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices")
            com.sf.module.esbinterface.webservice.stub.fileResendServices.FileResendServiceBodyType.SBODY sbody,
            @WebParam(name = "esbSoapHeader", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices", header = true)
            EsbSoapHeaderType esbSoapHeader,
            @WebParam(mode = WebParam.Mode.OUT, name = "SHEAD", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices")
            javax.xml.ws.Holder<com.sf.module.esbinterface.webservice.stub.fileResendServices.FileResendServiceResponseBodyType.SHEAD> shead1,
            @WebParam(mode = WebParam.Mode.OUT, name = "SBODY", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices")
            javax.xml.ws.Holder<com.sf.module.esbinterface.webservice.stub.fileResendServices.FileResendServiceResponseBodyType.SBODY> sbody1,
            @WebParam(mode = WebParam.Mode.OUT, name = "esbSoapHeader", targetNamespace = "http://www.sf-express.com/esb/service/FileResendServices", header = true)
            javax.xml.ws.Holder<EsbSoapHeaderType> esbSoapHeader1
    );
}
