
package com.sf.module.esbinterface.webservice.stub.fileResendServices;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.10
 * Tue Aug 26 14:45:32 CST 2014
 * Generated source version: 2.2.10
 */

public class ESBServerPortType_ESBServerSoapEndpoint_Server {

    protected ESBServerPortType_ESBServerSoapEndpoint_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ESBServerPortTypeImpl();
        String address = "http://www.sf-express.com/esb/services";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new ESBServerPortType_ESBServerSoapEndpoint_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
