CREATE OR REPLACE PROCEDURE P_HAND_DRIVE_CONVERT_AND_SCH AS

BEGIN
  -- 处理排班数据触发的数据对比任务
  PKG_HANDLE_COMPARE_REPORT.p_report_cause_by_schedule;
  
  -- 处理行车数据触发的数据对比任务
  PKG_HANDLE_COMPARE_REPORT.P_REPORT_CAUSE_BY_DRIVING;
  
END P_HAND_DRIVE_CONVERT_AND_SCH;
/
