--初始化数据
INSERT INTO TL_SPMS_SYS_CONFIG(ID, KEY_NAME, KEY_VALUE, KEY_DESC, CREATED_TM, MODIFIED_TM)
VALUES(SEQ_BASE.NEXTVAL, 'CD_SAP2SPMS_EMP', '0', 'SPMS同步SAP雇员接口数据处理开关：0表示关，1表示开', SYSDATE, NULL);
INSERT INTO TL_SPMS_SYS_CONFIG(ID, KEY_NAME, KEY_VALUE, KEY_DESC, CREATED_TM, MODIFIED_TM)
VALUES(SEQ_BASE.NEXTVAL, 'CD_HRS2SPMS_EMP', '1', 'SPMS同步HRS雇员接口数据处理开关：0表示关，1表示开', SYSDATE, NULL);
COMMIT;
