

CREATE TABLE TT_DRIVER_LINE_CONFIGURE (
      ID NUMBER(20) PRIMARY KEY NOT NULL,
      CODE VARCHAR2(20),
	  DEPARTMENT_CODE VARCHAR2(30),
      VALID_STATUS      NUMBER(1) DEFAULT 1,
	  TYPE      NUMBER(1) DEFAULT 1,
      CREATE_TM         DATE,
      MODIFIED_TM       DATE,
      CREATE_EMP_CODE   VARCHAR2(20),
      MODIFIED_EMP_CODE VARCHAR2(20)
);

-- ADD COMMENTS TO THE COLUMNS
COMMENT ON TABLE TT_DRIVER_LINE_CONFIGURE
  IS '线路配置信息表';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.ID
  IS '编号';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.CODE
  IS '配班代码';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.DEPARTMENT_CODE
  IS '网点代码';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.VALID_STATUS
  IS '是否有效  0：无效   1：有效';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.TYPE
  IS '配置类型  1 ：正常配班  0：机动配班';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.CREATE_TM
  IS '创建时间';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.MODIFIED_TM
  IS '修改时间';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.CREATE_EMP_CODE
  IS '创建人';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE.MODIFIED_EMP_CODE
  IS '修改人';
  

create sequence SEQ_TT_LINE_CONFIGURE
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20; 
  
CREATE TABLE TT_DRIVER_LINE_CONFIGURE_R (
      CONFIGURE_ID NUMBER(20),
      LINE_ID NUMBER(20),
      SORT	NUMBER(3)
);

-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE_R.CONFIGURE_ID
  IS '配班编号';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE_R.LINE_ID
  IS '关联线路编号';
COMMENT ON COLUMN TT_DRIVER_LINE_CONFIGURE_R.SORT
  IS '线路排序序号';