create sequence SEQ_OP_SCH_STATIS_REPORT
minvalue 1
maxvalue 999999999999999999999999999
start with 1
increment by 1
cache 20;

create table TT_OP_SCH_STATIS_REPORT
(
  ID                    NUMBER(18),
  hq_code               varchar2(30),
  YEAR_MONTH            VARCHAR2(7),
  AREA_CODE             VARCHAR2(30),
  DEPARTMENT_CODE       VARCHAR2(30),
  INNER_EMP             NUMBER,
  OUTER_EMP             NUMBER,
  GROUP_NUMBER          NUMBER,
  GROUPING_NUMBER       NUMBER,
  CLASS_NUMBER          NUMBER,
  CONFIRM_PROCESS       NUMBER,
  SCH_CONFIRM_INNER_EMP NUMBER,
  SCH_CONFIRM_OUTER_EMP NUMBER,
  PROCESS_SCH_INNER_EMP NUMBER,
  PROCESS_SCH_OUTER_EMP NUMBER,
  SCH_COMPLETE_RATE     NUMBER(10,4),
  SYS_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.ID IS 'ID';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.hq_code IS '经营本部';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.YEAR_MONTH IS '年月(YYYY-MM)';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.AREA_CODE IS '区部代码';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.DEPARTMENT_CODE IS '网店代码';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.INNER_EMP IS '内部人员数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.OUTER_EMP IS '外包人员数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.GROUP_NUMBER IS '小组数';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.GROUPING_NUMBER IS '已分组人数';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.CLASS_NUMBER IS '班别数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.CONFIRM_PROCESS IS '确认工序数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.SCH_CONFIRM_INNER_EMP IS '排班确认内部人员数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.SCH_CONFIRM_OUTER_EMP IS '排班确认外包人员数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.PROCESS_SCH_INNER_EMP IS '工序确认内部人员数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.PROCESS_SCH_OUTER_EMP IS '工序确认外包人员数量';
COMMENT ON COLUMN TT_OP_SCH_STATIS_REPORT.SCH_COMPLETE_RATE IS '完成率';

COMMENT ON TABLE TT_OP_SCH_STATIS_REPORT  IS '运作排班录入统计报表';