CREATE OR REPLACE VIEW V_SCHEDULING_FOR_DRIVER AS
SELECT T.VEHICLE_NUMBER,T.BELONG_ZONE_CODE,T.SOURCE_CODE,T.DESTINATION_CODE,T.START_TIME,T.END_TIME,D.DAY_OF_MONTH,D.DEPARTMENT_CODE,
D.EMPLOYEE_CODE,D.MODIFIED_TIME,T.SORT
  FROM TT_DRIVER_SCHEDULING D,
       (SELECT C.DEPARTMENT_CODE || '-' || C.CODE AS CONFIGURE_CODE,
               C.MONTH,
               C.DEPARTMENT_CODE,
               L.START_TIME,
               L.END_TIME,
               L.VEHICLE_NUMBER,
               L.BELONG_ZONE_CODE,
               L.SOURCE_CODE,
               L.DESTINATION_CODE,
               CR.SORT
          FROM TT_DRIVER_LINE_CONFIGURE   C,
               TT_DRIVER_LINE_CONFIGURE_R CR,
               TM_DRIVER_LINE             L
         WHERE C.ID = CR.CONFIGURE_ID
           AND CR.LINE_ID = L.ID ) T,
           TM_OSS_EMPLOYEE E,
           TM_DEPARTMENT DEPT
     WHERE E.DEPT_ID = DEPT.DEPT_ID
     AND DEPT.DEPT_CODE = D.DEPARTMENT_CODE
     AND E.EMP_CODE = D.EMPLOYEE_CODE
     AND D.CONFIGURE_CODE = T.CONFIGURE_CODE
     AND D.YEAR_MONTH = T.MONTH
	and d.scheduling_type = '1'
     GROUP BY T.VEHICLE_NUMBER,T.BELONG_ZONE_CODE,T.SOURCE_CODE,T.DESTINATION_CODE,T.START_TIME,T.END_TIME,D.DAY_OF_MONTH,D.DEPARTMENT_CODE,
D.EMPLOYEE_CODE,D.MODIFIED_TIME,T.SORT;
