-- ADD/MODIFY COLUMNS 
ALTER TABLE TT_DRIVER_MESSAGE ADD HOST_NAME VARCHAR2(100);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN TT_DRIVER_MESSAGE.STATUS
  IS '状态 0：未发送 1：发送成功 2：发送失败 3：发送中';
COMMENT ON COLUMN TT_DRIVER_MESSAGE.HOST_NAME
  IS '执行任务的主机名称';
  
-- ADD/MODIFY COLUMNS 
ALTER TABLE TT_DRIVER_MESSAGE_HIS ADD HOST_NAME VARCHAR2(100);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN TT_DRIVER_MESSAGE_HIS.STATUS
  IS '状态 0：未发送 1：发送成功 2：发送失败 3：发送中';
COMMENT ON COLUMN TT_DRIVER_MESSAGE_HIS.HOST_NAME
  IS '执行任务的主机名称';
  
-- ADD/MODIFY COLUMNS 
ALTER TABLE TT_SAP_DRIVER_LOG ADD HOST_NAME VARCHAR2(100);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN TT_SAP_DRIVER_LOG.STATUS
  IS '同步状态： 0：未同步  1：同步成功 2：同步失败 3：推送中';
COMMENT ON COLUMN TT_SAP_DRIVER_LOG.HOST_NAME
  IS '执行任务的主机名称';
  
-- ADD/MODIFY COLUMNS 
ALTER TABLE TT_SAP_DRIVER_LOG_HIS ADD HOST_NAME VARCHAR2(100);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN TT_SAP_DRIVER_LOG_HIS.STATUS
  IS '同步状态： 0：未同步  1：同步成功 2：同步失败 3：推送中';
COMMENT ON COLUMN TT_SAP_DRIVER_LOG_HIS.HOST_NAME
  IS '执行任务的主机名称';
  
BEGIN
  FOR JOB_ROW IN (SELECT JOB
                    FROM USER_JOBS
                   WHERE WHAT LIKE '%HANDLE_DRIVE_CONVER_DATA%') LOOP
    DBMS_JOB.REMOVE(JOB_ROW.JOB);
  END LOOP;
  COMMIT;
END;
/