package com.sf.module.esbinterface.webservice.stub.fileDeliveryServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Tue Aug 26 17:14:15 CST 2014
 * Generated source version: 2.2.10
 */

@WebService(targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ESBServerPortType {

    @RequestWrapper(localName = "FileDeliveryService", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices", className = "com.sf.module.esbinterface.webservice.stub.fileDeliveryServices.FileDeliveryServiceBodyType")
    @WebMethod(operationName = "FileDeliveryService", action = "urn:/FileDeliveryService")
    @ResponseWrapper(localName = "FileDeliveryServiceResponse", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices", className = "com.sf.module.esbinterface.webservice.stub.fileDeliveryServices.FileDeliveryServiceResponseBodyType")
    public void fileDeliveryService(
            @WebParam(name = "SHEAD", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices")
            com.sf.module.esbinterface.webservice.stub.fileDeliveryServices.FileDeliveryServiceBodyType.SHEAD shead,
            @WebParam(name = "SBODY", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices")
            com.sf.module.esbinterface.webservice.stub.fileDeliveryServices.FileDeliveryServiceBodyType.SBODY sbody,
            @WebParam(name = "esbSoapHeader", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices", header = true)
            EsbSoapHeaderType esbSoapHeader,
            @WebParam(mode = WebParam.Mode.OUT, name = "SHEAD", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices")
            javax.xml.ws.Holder<com.sf.module.esbinterface.webservice.stub.fileDeliveryServices.FileDeliveryServiceResponseBodyType.SHEAD> shead1,
            @WebParam(mode = WebParam.Mode.OUT, name = "SBODY", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices")
            javax.xml.ws.Holder<com.sf.module.esbinterface.webservice.stub.fileDeliveryServices.FileDeliveryServiceResponseBodyType.SBODY> sbody1,
            @WebParam(mode = WebParam.Mode.OUT, name = "esbSoapHeader", targetNamespace = "http://www.sf-express.com/esb/service/FileDeliveryServices", header = true)
            javax.xml.ws.Holder<EsbSoapHeaderType> esbSoapHeader1
    );
}
