
package com.sf.module.esbinterface.webservice.stub.fileDeliveryServices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.10
 * Tue Aug 26 17:14:15 CST 2014
 * Generated source version: 2.2.10
 */

public final class ESBServerPortType_ESBServerSoapEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://www.sf-express.com/esb/service/FileDeliveryServices/wsdl", "FileDeliveryServices");

    private ESBServerPortType_ESBServerSoapEndpoint_Client() {
    }
}
