
package com.sf.module.esbinterface.webservice.server.errorinfo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-10-31T16:40:22.619+08:00
 * Generated source version: 2.7.6
 * 
 */
 
public class BigFileServicePortType_BigFileServiceEndpoint_Server{

    protected BigFileServicePortType_BigFileServiceEndpoint_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new BigFileServicePortTypeImpl();
        String address = "http://www.sf-express.com/esb/service/BigFileService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new BigFileServicePortType_BigFileServiceEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
